[book]
author = [
"Aung Myat Moe (@amm834)",
]

language = "en"
multilingual = true
src = "src"
title = "Developement Environment Setup For Android Linux"

<<<<<<< HEAD

[build]
build-dir = "docs"
=======
>>>>>>> main
